esphome:
  name: freenove-cam
  name_add_mac_suffix: true
  platform: esp32
  board: esp32cam

wifi:
  <<: !include ../wifi_config.yaml

# HASS API
api:

# Allow API
ota:

# Print Updates
logger:

# WebServer component, displays some information
web_server:
    port: 80

esp32_camera:
  name: Freenove Camera
  external_clock:
    pin: GPIO21
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO4, GPIO5, GPIO18, GPIO19, GPIO36, GPIO39, GPIO34, GPIO35]  # Y2 ... Y9, order matters
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  resolution: 320x240  
  jpeg_quality: 10
  agc_mode: manual
  agc_value: 1
  # agc_gain_ceiling: 16x
  wb_mode: home

esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot
 
light:
  - platform: binary
    name: "Freenove LED"
    output: led

output:
  - id: led
    platform: gpio
    pin: GPIO2
