M48
; DRILL file {KiCad 7.0.8} date Sun Apr 21 12:19:54 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-21T12:19:54-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0295
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.0413
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C0.0454
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T6C0.0610
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T7C0.0807
%
G90
G05
T1
X-2.7012Y1.2161
X-2.7012Y0.9886
T2
X-0.8132Y-0.144
T3
X-0.1975Y-0.2969
X-0.1575Y-0.0969
X-0.1175Y-0.2969
T4
X-0.919Y-0.2497
T5
X-2.6772Y1.4567
X-2.6772Y-0.4724
X2.874Y1.4567
T7
X1.6535Y-0.1969
T6
G00X1.6535Y-0.0069
M15
G01X1.6535Y-0.0325
M16
G05
T0
M30
