substitutions:
  name: "DeskLamp"

esphome:
  name: ducky-iotleddriver
  name_add_mac_suffix: true
  platform: esp32
  board: esp32-s3-devkitc-1  # 8MB flash without PSRAM

wifi:
  <<: !include ../wifi_config.yaml

# HASS API
api:

# Allow API
ota:

# Print Updates
logger:

# WebServer component, displays some information
web_server:
    port: 80

light:
  - platform: binary
    name: "${name} DbgRed"
    internal: true
    output: led_red
  - platform: neopixelbus
    id: pixels
    variant: sk6812
    pin: GPIO5
    num_leds: 18
    name: "${name} Neopixels"
    effects:
      - addressable_rainbow:
          name: Rainbow
  - platform: monochromatic
    id: led_w
    name: "${name} White"
    output: ledw_out
  - platform: rgb
    id: led_rgb
    name: "${name} RGB"
    red: ledr_out
    green: ledg_out
    blue: ledb_out

output:
  - id: led_red
    platform: gpio
    pin: GPIO20
  - platform: ledc
    pin: GPIO1
    id: ledw_out
  - platform: ledc
    pin: GPIO2
    id: ledr_out
  - platform: ledc
    pin: GPIO42
    id: ledg_out
  - platform: ledc
    pin: GPIO40
    id: ledb_out

binary_sensor:
  - platform: gpio
    name: "${name} Encoder Sw"
    pin: 
      number: GPIO6
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on: 10ms
    on_click:
    - then:
        - lambda: |-
            auto ledw = id(led_w);
            auto ledrgb = id(led_rgb);
            if (!ledw->remote_values.is_on() && !ledrgb->remote_values.is_on()) {  // currently off, turn on
              ledw->turn_on().perform();
            } else {  // any light on, turn off all
              ledw->turn_off().perform();
              ledrgb->turn_off().perform();
            }

sensor:
  - platform: adc
    name: "${name} Vin"
    pin: GPIO4
    accuracy_decimals: 2
    update_interval: 60s
    attenuation: 11dB
    filters:
      - multiply: 4.29
  - platform: rotary_encoder
    name: "${name} Encoder"
    pin_a:
      number: GPIO15
      inverted: true
      mode:
        input: true
        pullup: true
    pin_b:
      number: GPIO7
      inverted: true
      mode:
        input: true
        pullup: true
    on_clockwise:
    - then:
        - lambda: |-
            auto ledw = id(led_w);
            auto call = ledw->turn_on();
            if (ledw->remote_values.is_on()) {  // first turn when off only turns on without changing level
              call.set_brightness(ledw->remote_values.get_brightness() + 0.1);
            }
            call.perform();
    on_anticlockwise:
    - then:
        - lambda: |-
            auto ledw = id(led_w);
            if (ledw->remote_values.get_brightness() <= 0.1) {
              ledw->turn_off().perform();
            } else {
              auto call = ledw->turn_on();
              call.set_brightness(ledw->remote_values.get_brightness() - 0.1);
              call.perform();
            }
